MAKE_TYPE := library

TARGET	 := libhydla_simulator.a
INCLUDES += -I. -I../parser -I../constraint_hierarchy -I../common -I../symbolic_simulator -I../output
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
