MAKE_TYPE := library

TARGET	 := libhydla_symbolic_simulator.a
INCLUDES += -I. -I../../parser -I../../constraint_hierarchy -I../ -I../../common -I../../backend -I../../backend/mathematica -I../../backend/reduce
LIBS	 += -lML64i3 -lm -lrt

DEFINES  += 
CXX_OPT  += 

include ../../Makefile.common
