MAKE_TYPE := library

TARGET	 := libhydla_output.a
INCLUDES += -I. -I../common -I../parser -I../simulator -I../constraint_hierarchy -I../backend
INCLUDES += -I/usr/local/include/boost-1_38
LDFLAGS	 += -L/usr/local/lib
LIBS	 +=
DEFINES  +=
CXX_OPT  +=

include ../Makefile.common
