MAKE_TYPE := library

TARGET	 := libhydla_symbolic_expression.a
INCLUDES += -I. -I../common -I../parser/error -I../simulator/
INCLUDES += -I/usr/local/include/boost
LDFLAGS	 += -L/usr/local/lib
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
