MAKE_TYPE := library

TARGET	 := libhydla_hierarchy.a
INCLUDES += -I. -I../parser -I../symbolic_expression
INCLUDES += -I/usr/local/include/boost
LDFLAGS	 += -L/usr/local/lib
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
