MAKE_TYPE := library

TARGET	 := libhydla_debug.a
INCLUDES += -I. -I../parser -I../simulator -I../common -I../hierarchy -I../simulator/symbolic_simulator -I../backend -I../symbolic_expression -I../parser/error
LIBS	 += -lm -lrt
DEFINES  += 
CXX_OPT  += -DAFFINE_SIMPLE=1

include ../Makefile.common

