MAKE_TYPE := library

TARGET	 := libhydla_parser.a
INCLUDES += -I. -I../common -I./error -I../symbolic_expression -I../utility
INCLUDES += -I/usr/local/include/boost
LDFLAGS	 += -L/usr/local/lib
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

DEP_OBJECTS  := ../parser/never_claim/libhydla_nc_parser.a

include ../Makefile.common
