MAKE_TYPE := library

TARGET	 := libhydla_parser.a
INCLUDES += -I. -I../common -I./error -I../symbolic_expression -I../utility -I../io
INCLUDES += -I/usr/local/include/boost
LDFLAGS	 += -L/usr/local/lib
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
