#ifndef _INCLUDED_HYDLA_PARSER_DEFAULT_NODE_FACTORY_H_
#define _INCLUDED_HYDLA_PARSER_DEFAULT_NODE_FACTORY_H_

#include "NodeFactory.h"

namespace hydla { 
namespace parser {

#define DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(NAME) \
  virtual boost::shared_ptr<hydla::parse_tree::NAME>            \
  create(hydla::parse_tree::NAME) const                   \
  { \
    return boost::make_shared<hydla::parse_tree::NAME>(); \
  }

class DefaultNodeFactory :  public NodeFactory
{
public:

protected:
  //定義
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(ProgramDefinition)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(ConstraintDefinition)

  //呼び出し
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(ProgramCaller)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(ConstraintCaller)
  
  //制約式
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Constraint);

  //Tell制約
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Tell)

  //Ask制約
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Ask)

  //比較演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Equal)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(UnEqual)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Less)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(LessEqual)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Greater)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(GreaterEqual)

  //論理演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(LogicalAnd)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(LogicalOr)

  //算術二項演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Plus)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Subtract)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Times)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Divide)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Power)
  
  //算術単項演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Negative)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Positive)

  //制約階層定義演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Weaker)
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Parallel)

  // 時相演算子
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Always)

  //微分
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Differential)
  
  //左極限
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Previous)
  
  //直前のPPの値
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(PreviousPoint)

  //変数・束縛変数
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Variable)

  //数字
  DEFAULT_NODE_FACTORY_DEFILE_NODE_CREATE_FUNC(Number)
};


} //namespace parser
} //namespace hydla

#endif //_INCLUDED_HYDLA_PARSER_DEFAULT_NODE_FACTORY_H_