MAKE_TYPE := library

TARGET	 := libhydla_common.a
INCLUDES += -I. 
INCLUDES += -I/usr/local/include/boost
LDFLAGS	 += -L/usr/local/lib
LIBS	 += 
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
