MAKE_TYPE := library

TARGET	 := libhydla_interval.a
INCLUDES += -I. -I../parser -I../simulator -I../common -I../constraint_hierarchy -I../simulator/symbolic_simulator -I../backend
LIBS	 += -lm -lrt
DEFINES  += 
CXX_OPT  += -DAFFINE_SIMPLE=1

include ../Makefile.common
