MAKE_TYPE := library

TARGET	 := libhydla_io.a
INCLUDES += -I. -I../common -I../parser -I../simulator -I../hierarchy -I../backend -I../symbolic_expression -I../parser/error -I../utility
LDFLAGS	 += -L/usr/local/lib
LIBS	 +=
DEFINES  +=
CXX_OPT  +=

include ../Makefile.common
