MAKE_TYPE := library

TARGET	 := libhydla_solver.a
INCLUDES += -I.
INCLUDES += -I../parser -I../constraint_hierarchy -I../simulator -I../common -I../backend -I../symbolic_simulator
DEFINES  += -DRP_SYSTEM_LINUX_IX86
CXX_OPT  += 

include ../Makefile.common