runs:
  using: "composite"
  steps:
    - name: print version
      run: |
        g++ --version | head -n 1
        clang++ --version | head -n 1
        python3 --version
      shell: bash
    - name: install boost
      run: |
        sudo apt install libboost-all-dev
      shell: bash
    - name: install mathematica
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX -O WolframEngine_LINUX.sh
        sudo bash WolframEngine_LINUX.sh
        export MATHPATH="/usr/local/Wolfram/WolframEngine/12.3"
      shell: bash
    - name: setting libraries
      run: |
        sudo chmod 777 /etc/ld.so.conf
        echo "$MATHPATH/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions" >> /etc/ld.so.conf
        sudo ldconfig
      shell: bash
