MAKE_TYPE := library

TARGET	 := libhydla_interval.a
INCLUDES += -I. -I../parser -I../simulator -I../common -I../constraint_hierarchy -I../symbolic_simulator
LIBS	 += -lm -lrt
DEFINES  += 
CXX_OPT  += 

include ../Makefile.common
