name: build-on-ubuntu
on:
  push:
    branches:
      - '*'
jobs:
  ubuntu18_04-clang9_0_0-python3_6_9:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: print version
      run: |
        g++ --version | head -n 1
        clang++ --version | head -n 1
        python3 --version
    - name: install boost
      run: |
        sudo apt install libboost-all-dev
    - name: install mathematica
      run: |
        wget https://files.wolframcdn.com/WolframEngine/12.1.1.0/WolframEngine_12.1.1_LINUX.sh
        sudo bash WolframEngine_12.1.1_LINUX.sh
    - name: setting libraries
      run: |
        cd /lib/x86_64-linux-gnu
        sudo ln -s libuuid.so.1.3.0 libuuid.so
        sudo chmod 777 /etc/ld.so.conf
        echo "/usr/local/Wolfram/WolframEngine/12.1/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions" >> /etc/ld.so.conf
        sudo ldconfig
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/12.1 CC=clang CXX=clang++
  ubuntu18_04-gcc7_5_0-python3_6_9:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: print version
      run: |
        g++ --version | head -n 1
        clang++ --version | head -n 1
        python3 --version
    - name: install boost
      run: |
        sudo apt install libboost-all-dev
    - name: install mathematica
      run: |
        wget https://files.wolframcdn.com/WolframEngine/12.1.1.0/WolframEngine_12.1.1_LINUX.sh
        sudo bash WolframEngine_12.1.1_LINUX.sh
    - name: setting libraries
      run: |
        cd /lib/x86_64-linux-gnu
        sudo ln -s libuuid.so.1.3.0 libuuid.so
        sudo chmod 777 /etc/ld.so.conf
        echo "/usr/local/Wolfram/WolframEngine/12.1/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions" >> /etc/ld.so.conf
        sudo ldconfig
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/12.1 CC=gcc CXX=g++
  ubuntu20_04-clang10_0_0-python3_8_5:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: print version
      run: |
        g++ --version | head -n 1
        clang++ --version | head -n 1
        python3 --version
    - name: install boost
      run: |
        sudo apt install libboost-all-dev
    - name: install mathematica
      run: |
        wget https://files.wolframcdn.com/WolframEngine/12.1.1.0/WolframEngine_12.1.1_LINUX.sh
        sudo bash WolframEngine_12.1.1_LINUX.sh
    - name: setting libraries
      run: |
        cd /lib/x86_64-linux-gnu
        sudo ln -s libuuid.so.1.3.0 libuuid.so
        sudo chmod 777 /etc/ld.so.conf
        echo "/usr/local/Wolfram/WolframEngine/12.1/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions" >> /etc/ld.so.conf
        sudo ldconfig
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/12.1 CC=clang CXX=clang++
  ubuntu20_04-gcc9_3_0-python3_8_5:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: print version
      run: |
        g++ --version | head -n 1
        clang++ --version | head -n 1
        python3 --version
    - name: install boost
      run: |
        sudo apt install libboost-all-dev
    - name: install mathematica
      run: |
        wget https://files.wolframcdn.com/WolframEngine/12.1.1.0/WolframEngine_12.1.1_LINUX.sh
        sudo bash WolframEngine_12.1.1_LINUX.sh
    - name: setting libraries
      run: |
        cd /lib/x86_64-linux-gnu
        sudo ln -s libuuid.so.1.3.0 libuuid.so
        sudo chmod 777 /etc/ld.so.conf
        echo "/usr/local/Wolfram/WolframEngine/12.1/SystemFiles/Links/WSTP/DeveloperKit/Linux-x86-64/CompilerAdditions" >> /etc/ld.so.conf
        sudo ldconfig
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/12.1 CC=gcc CXX=g++
