name: build-on-ubuntu
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'
jobs:
  ubuntu22_04-clang:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-ubuntu
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/14.0 CC=clang CXX=clang++
  ubuntu22_04-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-ubuntu
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/14.0 CC=gcc CXX=g++
  
  ubuntu24_04-clang:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-ubuntu
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/14.0 CC=clang CXX=clang++
  ubuntu24_04-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-ubuntu
    - name: build
      run: |
        make -j 4 MATHPATH=/usr/local/Wolfram/WolframEngine/14.0 CC=gcc CXX=g++
